package view;


public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_parcels = new javax.swing.JButton();
        btn_cutomers = new javax.swing.JButton();
        btn_processView = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        view_panel = new javax.swing.JPanel();
        title_panel = new javax.swing.JPanel();
        title_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_panel.setBackground(new java.awt.Color(0, 153, 153));
        main_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Navigations", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_parcels.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_parcels.setText("Parcels");
        btn_parcels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parcelsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_parcels, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 134, 31));

        btn_cutomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cutomers.setText("Cutomers");
        btn_cutomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cutomersActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cutomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        btn_processView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_processView.setText("Process View");
        btn_processView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processViewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_processView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 30));

        btn_exit.setBackground(new java.awt.Color(255, 51, 51));
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setText("Exit");
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, -1));

        main_panel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 400));

        view_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        view_panel.setOpaque(false);

        javax.swing.GroupLayout view_panelLayout = new javax.swing.GroupLayout(view_panel);
        view_panel.setLayout(view_panelLayout);
        view_panelLayout.setHorizontalGroup(
            view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        view_panelLayout.setVerticalGroup(
            view_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        main_panel.add(view_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 630, 390));

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 830, 410));

        title_panel.setBackground(new java.awt.Color(0, 51, 102));
        title_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title_lbl.setForeground(new java.awt.Color(255, 255, 255));
        title_lbl.setText("           Depot Management System");
        title_panel.add(title_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 10, 330, 30));

        getContentPane().add(title_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_parcelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parcelsActionPerformed

    view_panel.removeAll();
    ViewParcels parcelsPanel = new ViewParcels();
    parcelsPanel.setBounds(0, 0, view_panel.getWidth(), view_panel.getHeight());
    
    view_panel.add(parcelsPanel);
      view_panel.repaint();
      view_panel.revalidate();
    }//GEN-LAST:event_btn_parcelsActionPerformed

    private void btn_cutomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cutomersActionPerformed

    view_panel.removeAll();
    ViewCustomers customerPanel = new ViewCustomers();
    customerPanel.setBounds(0, 0, view_panel.getWidth(), view_panel.getHeight());
    
    view_panel.add(customerPanel);
        view_panel.repaint();
        view_panel.revalidate();
    }//GEN-LAST:event_btn_cutomersActionPerformed

    private void btn_processViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processViewActionPerformed

    view_panel.removeAll();
    ProcessPanel processPanel = new ProcessPanel();
    processPanel.setBounds(0, 0, view_panel.getWidth(), view_panel.getHeight());

    view_panel.add(processPanel);
        view_panel.repaint();
        view_panel.revalidate();
    
    }//GEN-LAST:event_btn_processViewActionPerformed

   
    public static void main(String args[]) {
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cutomers;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_parcels;
    private javax.swing.JButton btn_processView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel title_lbl;
    private javax.swing.JPanel title_panel;
    private javax.swing.JPanel view_panel;
    // End of variables declaration//GEN-END:variables
    
    
    
}
